### ISSUE TITLE
unable to load the images of statistics getting some errors in logs 

### ISSUE THREAD

**Issue by ranjithchittuluri** [javamelody/liferay-javamelody#9]
Hi Team, 

I am facing a strange issue in the liferay-java-melody hook 
i am deploying this on standalone environment of jboss
[javamelody_error.txt](https://github.com/javamelody/liferay-javamelody/files/912656/javamelody_error.txt)
![error](https://cloud.githubusercontent.com/assets/8276085/24901033/7eff5ddc-1eae-11e7-8e73-6fefac35205e.png)
d

**Comment by ranjithchittuluri** [comment]
i am unable to load the statics image

**Comment by evernat** [comment]
Given the stack-trace, you are running Liferay using jbossweb-7.2.2.Final-redhat-1 and JDK 1.7.0_79.

First, a question: is there a reason you are using jbossweb instead of the default Tomcat container?
And is it reproductible with the "Bundled with wildfly" Liferay download? and with the "Bundled with tomcat" Liferay download?
Then, an information: "NoClassDefFoundError: sun/nio/ch/DirectBuffer" means that there is probably a problem with OSGi configuration which for some reason prevents javamelody to load the sun.nio.ch.DirectBuffer class.

**Comment by evernat** [comment]
Any news?

**Comment by evernat** [comment]
No response from the reporter, so closing as incomplete.
